name: Injection-Demo

on:
    issues:
        types: [opened]
jobs: 
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Print Issue title
              run: echo "${{github.event.issue.title}}"