name: Injection-Demo

on:
    issues:
        types: [opened]
jobs: 
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Print Issue title
              env:
                ISSUE_TITLE: ${{github.event.issue.title}}
              run: echo "$ISSUE_TITLE"
               